name: Terraform Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '00-modules/**'
      - '05-infra/**'
  pull_request:
    paths:
      - '00-modules/**'
      - '05-infra/**'

jobs:
  terraform-plan-dev:
    name: Terraform Plan DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  terraform-plan-uat:
    name: Terraform Plan UAT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  terraform-plan-prod:
    name: Terraform Plan Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  terraform-apply-dev:
    name: Terraform Apply DEV
    needs: terraform-plan-dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  terraform-apply-uat:
    name: Terraform Apply UAT
    needs: [terraform-plan-uat, terraform-apply-dev]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  terraform-apply-prod:
    name: Terraform Apply Prod
    needs: [terraform-plan-prod, terraform-apply-uat]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
